# Generated by Django 3.2.9 on 2021-11-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PollUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polling_unit_id', models.PositiveBigIntegerField(unique=True)),
                ('ward_id', models.PositiveBigIntegerField()),
                ('lga_id', models.PositiveBigIntegerField()),
                ('uniquewardid', models.PositiveBigIntegerField()),
                ('polling_unit_number', models.CharField(blank=True, max_length=50)),
                ('polling_unit_name', models.CharField(blank=True, max_length=50)),
                ('polling_unit_description', models.TextField(blank=True)),
                ('lat', models.CharField(blank=True, max_length=255)),
                ('long', models.CharField(blank=True, max_length=255)),
                ('entered_by_user', models.CharField(max_length=50)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Poll unit',
                'verbose_name_plural': 'Poll unit',
            },
        ),
    ]
