# Generated by Django 3.2.9 on 2021-11-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollunit',
            name='user_ip_address',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
