# Generated by Django 3.2.9 on 2021-11-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20211117_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollunit',
            name='polling_unit_id',
            field=models.PositiveBigIntegerField(),
        ),
    ]
